apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: demo.example.com
  description: Demo Domain for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: default-team

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app-ms-1
  links:
    - url: https://ms1.default.apps.example.com
      title: Microservice 1 Entrypoint
      icon: dashboard
  description: Demo Application's Microservice-1
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=demo-app-ms-1'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  providesApis:
   - demo-api
  lifecycle: alpha
  owner: demo-team
  system: demo-app

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app-ms-2
  description: Demo Application's Microservice-2
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=demo-app-ms-2'
    'backstage.io/techdocs-ref': dir:.
  links:
  - url: https://ms2.default.apps.example.com
    title: Microservice 2 Entrypoint
    icon: dashboard
spec:
  type: service
  consumesApis:
   - demo-api
  lifecycle: alpha
  owner: demo-team
  system: demo-app
  

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: google-page
  description: Demo Access to google
  tags:
    - search
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=search'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://www.google.com
      title: Search Google
      icon: dashboard
spec:
  type: search
  consumesApis:
    - demo-api
  lifecycle: alpha
  owner: demo-team
  system: demo-app


---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-app
  description: Demo Application for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: demo-team
  domain: demo-domain

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: The demo API for Tanzu Application Platform GUI
  links:
    - url: https://www.agify.io
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: demo-team
  system: demo-app # Or specify system name of your choice
  definition: |
    openapi: 3.0.1
    info:
      title: agify.io API Demo
      description: This API Demos to query API using parameters
      version: '0.1'
    servers:
      - url: https://api.agify.io
    paths:
      /:
        get:
          description: This call return a user with a dummy location
          parameters:
            - in: query
              name: name
              schema:
                type: string
                example: Andreas
          responses:
            '200':
              description: Auto generated using Swagger Inspector
              content:
                application/json; charset=utf-8:
                  schema:
                    age: number
                    count: number
                    name: string
                  examples: {}
