apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: demo.example.com
  description: Demo Domain for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: default-team